version: "3.9"
name: "swa"
  
services:
  facade:
    build:
      context: .
      dockerfile: ./services/facade/Dockerfile
    ports:
      - "8080:8080"
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
    tty: true
    networks:
      - my-network
  logging:
    build:
      context: .
      dockerfile: ./services/logging/Dockerfile
    ports:
      - "8081"
    tty: true
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
    networks:
      - my-network
      - hazelcast-network
    deploy:
      replicas: 3
  message:
    build:
      context: .
      dockerfile: ./services/message/Dockerfile
    ports:
      - "8082:8082"
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
    tty: true
    networks:
      - my-network
  hazelcast:
    image: hazelcast/hazelcast
    networks:
      - hazelcast-network
    deploy:
      replicas: 3
      
networks:
  my-network:
    name: "my-network"
  hazelcast-network:
    name: "hazelcast-network"

