version: "3.9"
name: "swa"
  
services:
  facade:
    build:
      context: .
      dockerfile: ./services/facade/Dockerfile
    ports:
      - "8080:8080"
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "facade"
      KAFKA_ADDRESS: "kafka:9092"
    tty: true
    networks:
      - my-network
      - kafka-network
    depends_on:
      - kafka
  logging-1:
    build:
      context: .
      dockerfile: ./services/logging/Dockerfile
    ports:
      - "8081"
    tty: true
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "logging-1"
    networks:
      - my-network
      - hazelcast-network
  logging-2:
    build:
      context: .
      dockerfile: ./services/logging/Dockerfile
    ports:
      - "8081"
    tty: true
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "logging-2"
    networks:
      - my-network
      - hazelcast-network
  logging-3:
    build:
      context: .
      dockerfile: ./services/logging/Dockerfile
    ports:
      - "8081"
    tty: true
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "logging-3"
    networks:
      - my-network
      - hazelcast-network
  message-1:
    build:
      context: .
      dockerfile: ./services/message/Dockerfile
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "message-1"
      KAFKA_ADDRESS: "kafka:9092"
    tty: true
    networks:
      - my-network
      - kafka-network
    depends_on:
      - kafka
  message-2:
    build:
      context: .
      dockerfile: ./services/message/Dockerfile
    environment:
      FACADE_ENDPOINT: "facade"
      LOGGING_ENDPOINT: "logging"
      MESSAGE_ENDPOINT: "message"
      MY_ADDRESS: "message-2"
      KAFKA_ADDRESS: "kafka:9092"
    tty: true
    networks:
      - my-network
      - kafka-network
    depends_on:
      - kafka
  hazelcast:
    image: hazelcast/hazelcast
    networks:
      - hazelcast-network
    deploy:
      replicas: 3
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network
  kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    ports:
      - '29092:29092'
    expose:
      - '9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'
    networks:
      - kafka-network

  init-kafka:
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic messages --replication-factor 1 --partitions 2

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
    networks:
      - kafka-network
      
  consul:
    image: consul:latest
    ports:
      - "8500:8500"
    healthcheck:
      test: [ "CMD", "consul", "members" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - my-network
  setup-consul:
    image: consul:latest
    depends_on:
      consul:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "            
      consul kv put -http-addr=consul:8500 hazelcast/cluster_address "hazelcast" 
      consul kv put -http-addr=consul:8500 hazelcast/map_name "userMessages"
      consul kv put -http-addr=consul:8500 kafka/server "kafka:9092"
      consul kv put -http-addr=consul:8500 kafka/topic_name "messages"
      "
    networks:
      - my-network

networks:
  my-network:
    name: "my-network"
  hazelcast-network:
    name: "hazelcast-network"
  kafka-network:
    name: "kafka-network"

